"""Initial migration

Revision ID: 934359c50f37
Revises: fbabc6d1657f
Create Date: 2025-08-29 13:06:40.656807

"""



# revision identifiers, used by Alembic.
revision = '934359c50f37'
down_revision = 'fbabc6d1657f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
