"""Initial migration

Revision ID: fa44d1df7870
Revises: 934359c50f37
Create Date: 2025-08-29 13:09:23.404061

"""



# revision identifiers, used by Alembic.
revision = 'fa44d1df7870'
down_revision = '934359c50f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
