"""Initial migration

Revision ID: fbabc6d1657f
Revises: a7ceb406074f
Create Date: 2025-08-29 12:58:03.113788

"""



# revision identifiers, used by Alembic.
revision = 'fbabc6d1657f'
down_revision = 'a7ceb406074f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
