name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: microblog
          POSTGRES_PASSWORD: microblog
          POSTGRES_DB: microblog
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U microblog -d microblog"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r backend/requirements-dev.txt

      - name: Run Alembic migrations
        working-directory: ./backend
        run: |
          export DATABASE_URL=postgresql+psycopg2://microblog:microblog@localhost:5432/microblog
          alembic upgrade head

      - name: Run tests
        working-directory: ./backend
        run: |
          export DATABASE_URL=postgresql+psycopg2://microblog:microblog@localhost:5432/microblog
          pytest -q --disable-warnings --maxfail=1 --cov=app

      - name: Run ruff linter
        run: ruff check backend

      - name: Run mypy
        run: mypy backend
